name: Slack Notification

on:
  workflow_call:
    inputs:
      title:
        description: Title of the notification
        required: true
      message:
        description: The message to be sent
        required: true
      channel_id:
        description: The channel this message will be sent to
        required: true
      slack_bot_token:
        description: Slack bot token
        required: true
      github_token:
        description: GitHub token
        required: true
      
    outputs:
      message_ts:
        description: "Slack message timestamp"
        value: ${{ jobs.notify-start.outputs.message_ts }}

jobs:
  notify-start:
    runs-on: ubuntu-latest
    outputs:
      message_ts: ${{ steps.send.outputs.ts }}
    steps:
      - name: Send Slack Start Message
        id: send
        run: |
          response=$(curl -s -X POST -H "Content-type: application/json" \
            --data '{
              "text": "Workflow *${{ github.workflow }}* has started for repo `${{ github.repository }}` on branch `${{ github.ref_name }}`"
            }' "${{ inputs.slack_bot_token }}")
          echo "Response: $response"
          ts=$(echo $response | jq -r .ts)
          echo "ts=$ts" >> $GITHUB_OUTPUT

  notify-finish:
    runs-on: ubuntu-latest
    needs: notify-start
    if: always()
    steps:
      - name: Update Slack Message
        run: |
          curl -X POST -H "Content-type: application/json" \
          --data '{
            "text": "Workflow *${{ github.workflow }}* for repo `${{ github.repository }}` on branch `${{ github.ref_name }}` has *${{ job.status }}*.",
            "ts": "${{ needs.notify-start.outputs.message_ts }}"
          }' "${{ inputs.slack_bot_token }}"
