name: Call other repo

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            deployed: ${{ steps.set-output.outputs.success }}
        steps:
            - name: fake deploy
              id: fake
              run: |
                echo "this is a fake deploy step"
                sleep 2
            
            - name: Set output success flag
              id: set-output
              run: |
                  if [ "${{ steps.deploy-step.outcome }}" == "success" ]; then
                  echo "success=true" >> $GITHUB_OUTPUT
                  else
                  echo "success=false" >> $GITHUB_OUTPUT
                  fi

    notify-success:
        name: Slack Success Notification
        needs: deploy
        if: ${{ needs.deploy.outputs.deployed == 'true' }}
        uses: KomodoHQ/git-utils/.github/workflows/slack-notify.yml@main
        with:
            message: "Staging deploy succeeded for `${{ github.repository }}`"
        secrets:
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    notify-failure:
        name: Slack Failure Notification
        needs: deploy
        if: ${{ needs.deploy.outputs.deployed == 'false' }}
        uses: KomodoHQ/git-utils/.github/workflows/slack-notify.yml@main
        with:
            message: "Staging deploy failed for `${{ github.repository }}`"
        secrets:
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}