name: Call other repo

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            deployed: ${{ steps.set-output.outputs.success }}
        steps:
            - name: deploy
              id: deploy-step
              run: |
                echo "this is a fake deploy step"
                sleep 2
            
            - name: Set output success flag
              id: set-output
              run: |
                  if [ "${{ steps.deploy-step.outcome }}" == "success" ]; then
                  echo "success=true" >> $GITHUB_OUTPUT
                  else
                  echo "success=false" >> $GITHUB_OUTPUT
                  fi

    notify-success:
        name: Slack Success Notification
        needs: deploy
        if: ${{ needs.deploy.outputs.deployed == 'true' }}
        uses: KomodoHQ/git-utils/.github/workflows/slack-notify.yml@main
        with:
            status: "succeeded"
            repository: ${{ github.repository }}
            branch: ${{ github.ref_name }}
            actor: ${{ github.actor }}
            action_name: ${{ github.workflow }}
            commit_sha: ${{ github.sha }}`
        secrets:
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

    notify-failure:
        name: Slack Failure Notification
        needs: deploy
        if: ${{ needs.deploy.outputs.deployed == 'false' }}
        uses: KomodoHQ/git-utils/.github/workflows/slack-notify.yml@main
        with:
            status: "failed"
            repository: ${{ github.repository }}
            branch: ${{ github.ref_name }}
            actor: ${{ github.actor }}
            action_name: ${{ github.workflow }}
            commit_sha: ${{ github.sha }}`
        secrets:
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
